theme: jekyll-theme-dinky

title: Slides 
github_repository_name: presentations
github_repository_url: https://github.com/idia640/presentations
github_owner: Lisa D. Harper
github_owner_url: https://github.com/idia640

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

include: ["_pages"]

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

permalink: pretty

gems:
- jemoji
- jekyll-paginate
- jekyll-feed

 # This will require each of these plugins automatically.

# Kramdown options
# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html
# kramdown:
#   hard_wrap: true (already set to default)
