theme: jekyll-theme-minimal

title: Slides
github_repository_name: presentations
github_repository_url: https://github.com/idia640/presentations
github_owner: Lisa D. Harper
github_owner_url: https://github.com/idia640
baseurl: /presentations

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

include: ["_pages"]

# Assets
sass:
  sass_dir:          _sass
  style:            :compressed

permalink: pretty

gems:
- jemoji
- jekyll-feed


# gitpitch settings
revealjs: 3.4.1
slide-number: true
